name: VillagerTradeEvent
version: '${project.version}'
main: me.abetgt.villagertradeevent.TradeEventHandler
api-version: 1.19
authors: [ AbeTGT ]
description: Detect when players have traded with a villager, without the use of Paper server software.
website: http://oasisnetwork.cf
